services:
  db:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db-data:/var/lib/postgresql/data

  odoo18:
    image: odoo:18.0
    depends_on:
      - db
    ports:
      - "8068:8069"
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./enterprise:/mnt/enterprise
      - ./addons:/mnt/extra-addons
    command: odoo -d melvon3 -i base --db_user=odoo --db_password=odoo --db_host=db
    restart: always

volumes:
  odoo-web-data:
  odoo-db-data: